language: node_js
node_js:
  - node
script:
  - npm run travis
deploy:
  provider: pages
  verbose: true
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  keep-history: false
  target-branch: gh-pages
  on:
    branch: master
